# A simple action usage
name: Build Kernel
on:
  workflow_dispatch:

jobs:
  Build-Kernel:
    strategy:
      fail-fast: false
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Build Kernel
        uses: dabao1955/kernel_build_action@main
        with:
          kernel-url: https://github.com/Peridot-Development/kernel_xiaomi_peridot
          kernel-dir: msm-6.1
          kernel-branch: peridot-u-oss
          config: gki_defconfig
          arch: arm64
          aosp-gcc: true
          aosp-clang: true
          ksu: true
          ksu-version: main
          android-version: 14
          aosp-clang-version: r383902
          disable-lto: true
          anykernel3: true
